SomosCodear/codear-site

- src/pages/index.jsx
- changed CTA for WebConf button
> Release 19-12-2019 #2

- .eslintrc
- package.json
- src/components/Container.jsx
- src/components/Nav.jsx
- src/pages/_app.jsx
- src/pages/about.jsx
- src/pages/coc.jsx
- src/pages/index.jsx
- yarn.lock
- Menu fixes
- Small refactor of common layout
- Upgrade dependencies
> Release 22-12-2019

- src/components/Container.jsx
> Release 30-12-2019

- src/events.json
- Update events for february 2020
> Release 03-02-2020

- src/events.json
> Release 25-02-2020

- src/components/Container.jsx
> Adds brand acronym to the <title>

- src/components/Container.jsx
- src/pages/about.jsx
- Removes the group photo in "About us"
> Release 25-02-2020 (3)

- src/events.json
- Fixes wrong time data for most of the events
> Release 26-02-2020 (2)

- now.json
- src/events.json
- /media-kit/brandbook endpoint
> Release 29-02-2020

- src/pages/comuniques.jsx
- fixes security issues (see #34)
> Release 14-03-2020

- src/pages/index.jsx
> Fixes homepage bug with community icons

- now.json
- src/events.json
- src/pages/knowledge.jsx
- src/webinars.json
- Adds video of first of #EncuentrosCodear
> Release 26-03-2020

- .huskyrc
- next.config.js
- package.json
- src/components/Calendar/Calendar.jsx
- src/pages/communities.jsx
- src/pages/comuniques.jsx
- src/pages/index.jsx
- src/pages/knowledge.jsx
- yarn.lock
Upgrade dependencies, remove unused `next-css` and `next-fonts` helpers, add husky and did some small fixes due to linting and dep changes.
> Dependencies and small fixes

- next.config.js
- now.json
- src/data/config.js
- src/pages/_app.jsx
Move analytics to an env variable.
> feat(analytics): do per-env analytics based on branch

- now.json
> Release 31-03-2020 (2)

- src/events.json
- src/projects.json
- src/webinars.json
> Release 05-05-2020

- now.json
- Adds call-for-speakers form for #EncuentrosCodear
> Release 21-05-2020

- now.json
> Release 21-05-2020 (2)

- src/pages/knowledge.jsx
- src/webinars.json
We removed the listing of each event, leaving only the upcoming ones.
Also it adds a brand new YouTube player.
> Redesigns webinar page

- next.config.js
> Release 17-06-2020

- now.json
> Release 19-06-2020

- src/components/Container.jsx
- src/data/constants/meta.js
> Release 19-07-2020

- next.config.js
- package.json
- src/pages/api/next-encuentros-codear.js
- yarn.lock
Will be used as a Linktree link.
> Adds /encuentros/proximo route to autodetect next Eventbrite event

- src/pages/communities.jsx
- Country-less wording for Communities page
> Release 10-08-2020

- vercel.json
> Release 13-09-2020

- src/components/Calendar/Calendar.jsx
> Release 20-09-2020

- vercel.json
Adds the route redirection for the hacktoberfest code of conduct.
> Release 26-09-2020

- vercel.json
- Actualiza redirección de codear.org/hacktoberfest a link de transmisión en vivo de YouTube
> Release 09-10-2020

- src/data/constants/members.js
- Actualiza listado de miembros de Comisión Directiva
> Release 14-10-2020

- src/communities.json
- Actualiza links de FrontendCafe
> Release 02-10-2020

- src/pages/index.jsx
- Oculta banner de Hacktoberfest
> Release 02-11-2020

- vercel.json
- Redirect codear.org/honduras
> Release 07-11-2020

- src/components/Footer.jsx
> Agrega GitHub en lugar de Eventbrite

- next.config.js
> Release 05-06-2021
